# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 485)
        self.formLayoutWidget = QtWidgets.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 361, 191))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.id_line = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.id_line.setObjectName("id_line")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.id_line)
        self.fry_line = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fry_line.setObjectName("fry_line")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.fry_line)
        self.name_line = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.name_line.setObjectName("name_line")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.name_line)
        self.cond_line = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.cond_line.setObjectName("cond_line")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cond_line)
        self.taste_line = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.taste_line.setObjectName("taste_line")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.taste_line)
        self.cost_line = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.cost_line.setObjectName("cost_line")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.cost_line)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.V_line = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.V_line.setObjectName("V_line")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.V_line)
        self.add = QtWidgets.QPushButton(Form)
        self.add.setGeometry(QtCore.QRect(94, 230, 181, 23))
        self.add.setObjectName("add")
        self.change = QtWidgets.QPushButton(Form)
        self.change.setGeometry(QtCore.QRect(94, 270, 181, 23))
        self.change.setObjectName("change")
        self.test = QtWidgets.QLabel(Form)
        self.test.setGeometry(QtCore.QRect(150, 350, 47, 13))
        self.test.setObjectName("test")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "ID"))
        self.label_2.setText(_translate("Form", "название сорта"))
        self.label_3.setText(_translate("Form", "степень обжарки"))
        self.label_4.setText(_translate("Form", "молотый/в зернах"))
        self.label_5.setText(_translate("Form", "описание вкуса"))
        self.label_6.setText(_translate("Form", "цена"))
        self.label_7.setText(_translate("Form", "объем упаковки(ml)"))
        self.add.setText(_translate("Form", "Добавить запись"))
        self.change.setText(_translate("Form", "Изменить запись"))
        self.test.setText(_translate("Form", " "))
